### PR TITLE
Re-add ability to use old delegating behavior to ease upgrade path

### PR DESCRIPTION
**Pull request by pradtke**

### CODE REVIEW

**Comment by tvdijen** [comment]
How does this ease upgrading?

**Comment by pradtke** [comment]
By re-allowing the SSP 1.x way of configuring the delegate I can now use the same authsource.php configuration in both our SSP 2 testing and for SSP 1.X.   We have a lot of things to todo/validate for our SSP 2 upgrade, and changing how authsources are defined can now come post-SSP 2 upgrade. Plus I expect we'll run both in parallel for some time and slowly shift traffic, so it would nice to have the same config work for both.

**Comment by tvdijen** [comment]
This now means I have to update config for 25+ instances... Why didn't you create a migration-branch?

**Comment by pradtke** [comment]
I don’t think I understand. The change is to support both the old and new way, not just the new way.  I’ll ping you on slack when I’m home and we can discuss in realtime today or tomorrow (since I know it’s your night already).

**Comment by tvdijen** [comment]
Ah, forget what I said.. I thought the change was reverted completely..
Whether you can use the same authsources for both versions depends on the ones you are using.. Most have changed in 2.0

**Comment by pradtke** [comment]
Thanks for clarification, and thanks for the heads up about a lot of authsources changing in 2.0

**Comment by tvdijen** [comment]
Just out of curiosity;  which ones are you using?

**Comment by pradtke** [comment]
SP, Ldap, OAuth2, CAS, exampleauth for some test servers,  and some subclasses of the SP authsource

**Comment by tvdijen** [comment]
LDAP has changed significantly.. Not just the config items, but also the class-name was renamed from LDAP to Ldap..  No way you can use the same authsources-files for both versions

**Pull request merged**
